services:
  uwb_nxp:
    build:
      context: .
      dockerfile: Dockerfile
    image: uwb_nxp
    container_name: uwb_nxp
    privileged: true
    environment:
      LOCAL_USER_ID: ${LOCAL_USER_ID:-1000}
      LOCAL_GROUP_ID: ${LOCAL_GROUP_ID:-1000}
      LOCAL_GROUP_NAME: ${LOCAL_GROUP_NAME:-hostgroup}
    volumes:
      - ./:/home/ws/src
    stdin_open: true
    tty: true
    command: bash
